name: Deploy Blazor WASM app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bk
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore bgk.sln

      - name: Build
        run: dotnet build bgk.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish bgk.csproj --configuration Release --output ${{ github.workspace }}/publish --no-restore

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-wasm-app
          path: ${{ github.workspace }}/publish

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-wasm-app
          path: publish

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: publish
