name: Build and deploy ASP.NET Core app to Azure Web App - bk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Prevent overlapping runs to the same app (reduces 409s)
concurrency:
  group: webapp-bk
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: 'bk'
  DOTNET_VERSION: '9.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    permissions:
      contents: read

    steps:
      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build -o "${{ github.workspace }}/publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-publish
          path: ./publish  # ensures a predictable folder

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3491FAFD1B6F4689B94BCC58065EC5BB }}
