name: Build and deploy ASP.NET Core app to Azure Web App - bk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Prevent overlapping runs to the same app (reduces 409s)
concurrency:
  group: webapp-bk
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: 'bk'
  DOTNET_VERSION: '9.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          # If your App Service isn’t on .NET 9 yet, switch to '8.x'
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build -o "${{ github.workspace }}/publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-publish
          path: ./publish  # ensures a predictable folder

      - name: 'Deploy to Azure Web App (Attempt 1)'
        id: deploy-attempt-1
        continue-on-error: true
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3491FAFD1B6F4689B94BCC58065EC5BB }}

      - name: 'Wait for 90s on failure'
        if: ${{ steps.deploy-attempt-1.outcome == 'failure' }}
        run: sleep 90

      - name: 'Deploy to Azure Web App (Attempt 2)'
        if: ${{ steps.deploy-attempt-1.outcome == 'failure' }}
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3491FAFD1B6F4689B94BCC58065EC5BB }}
